---
- name: Create dir for jdk
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jdk_install_user }}"
    group: "{{ jdk_install_group }}"
    mode: 0755
  loop:
    - "{{ base_dir }}"
    - "{{ jdk_base_dir }}"

- name: Copy jdk_package_name to install_tmpdir
  copy:
    src: "{{ jdk_package_name }}"
    dest: "{{ install_tmpdir }}/"
    owner: "{{ jdk_install_user }}"
    group: "{{ jdk_install_group }}"
  when: jdk_package_name is defined

- name: Extract jdk_package_name jdk_base_dir
  unarchive:
    src: "{{ install_tmpdir }}/{{ jdk_package_name }}"
    dest: "{{ jdk_base_dir }}/"
    remote_src: true
    owner: "{{ jdk_install_user }}"
    group: "{{ jdk_install_group }}"
    extra_opts:
      - --strip-components=1
    # exclude:
    #   - "COPYRIGHT"
    #   - "LICENSE"
    #   - "README.html"
    #   - "release"
    #   - "THIRDPARTYLICENSEREADME-JAVAFX.txt"
    #   - "THIRDPARTYLICENSEREADME.txt"

# # 防止宿主机本身有java环境污染环境变量，后续会将java变量配置到zkEnv.sh中
# # add JAVA_HOME to /etc/profile
# - name: Add JAVA env variables to /etc/profile
#   become: yes
#   blockinfile:
#     dest: /etc/profile
#     block: |
#       export JAVA_HOME="{{ java_home }}"
#       export JRE_HOME="$JAVA_HOME/jre"
#       export CLASSPATH=".:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH"
#       export PATH="$JAVA_HOME/bin:$PATH"
#     marker: "# {mark} JDK environment variables"
#     state: present

# # java -version
# - name: "show {{ java_home }}/bin/java version"
#   shell: "{{ java_home }}/bin/java -version"




