---
- name: Apply check role
  hosts: all
  gather_facts: true
  roles:
    - {
        role: check,
        tags: check,
      }

# - name: Apply os role
#   hosts: all
#   gather_facts: true
#   roles:
#     - {
#         role: os,
#         tags: os,
#       }

- name: Apply mysql role
  hosts: all
  gather_facts: true
  roles:
    - {
        role: db,
        tags: db,
      }

- name: Apply zookeeper role
  hosts: all
  gather_facts: true
  roles:
    - {
        role: zookeeper,
        tags: zookeeper,
      }


- name: Apply greatdbrouter role
  hosts: all
  gather_facts: true
  roles:
    - {
        role: greatdbrouter,
        tags: greatdbrouter,
      }

# - name: Apply service role
#   hosts: all
#   gather_facts: true
#   roles:
#     - {
#         role: service,
#         tags: service,
#       }













