---
- name: Include DB default variables
  include_vars:
    file: roles/db/defaults/main.yml

- name: Include zookeeper default variables
  include_vars:
    file: roles/zookeeper/defaults/main.yml

- name: Include greatdbrouter default variables
  include_vars:
    file: roles/greatdbrouter/defaults/main.yml
  
- name: Get DB conf dir path
  shell:
    cmd: ls -rt {{ db_dbdata_dir }} | xargs  | awk '{print $NF}'
  register: db_uuid

